# Generated by Django 5.1.4 on 2026-06-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.CharField(blank=True, default='', max_length=200)),
                ('kcal_per_100g', models.FloatField(blank=True, null=True)),
                ('protein_per_100g', models.FloatField(blank=True, null=True)),
                ('fat_per_100g', models.FloatField(blank=True, null=True)),
                ('carbs_per_100g', models.FloatField(blank=True, null=True)),
                ('default_serving_g', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=8)),
                ('activity_level', models.CharField(blank=True, default='', max_length=32)),
                ('goal', models.CharField(blank=True, default='maintain', max_length=16)),
                ('daily_baseline_kcal', models.IntegerField(blank=True, null=True)),
                ('bmr', models.IntegerField(blank=True, null=True)),
                ('training_days_interval', models.IntegerField(blank=True, null=True)),
                ('target_kcal', models.IntegerField(blank=True, null=True)),
                ('target_protein_g', models.FloatField(blank=True, null=True)),
                ('target_fat_g', models.FloatField(blank=True, null=True)),
                ('target_carbs_g', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='fitness.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='BodyParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat_pct', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_params', to='fitness.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, default='', max_length=8)),
                ('description', models.TextField(blank=True, default='')),
                ('kcal', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('meal_type', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log', to='fitness.tguser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='fitness_foo_user_id_34fc45_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, default='', max_length=8)),
                ('activity', models.CharField(blank=True, default='', max_length=64)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('kcal_burned', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walking_log', to='fitness.tguser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='fitness_wal_user_id_c189a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.IntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_blocks', to='fitness.tguser')),
            ],
            options={
                'unique_together': {('user', 'block_num')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.IntegerField()),
                ('group', models.CharField(blank=True, default='', max_length=64)),
                ('exercise', models.CharField(max_length=200)),
                ('sets', models.CharField(blank=True, default='', max_length=16)),
                ('reps', models.CharField(blank=True, default='', max_length=16)),
                ('weight', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('met', models.FloatField(blank=True, null=True)),
                ('default_min', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='fitness.tguser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'block_num'], name='fitness_wor_user_id_498b35_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('block_num', models.IntegerField()),
                ('exercise', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_done', to='fitness.tguser')),
            ],
            options={
                'unique_together': {('user', 'date', 'block_num', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_plan', models.CharField(blank=True, default='', max_length=128)),
                ('exercises_done', models.TextField(blank=True, default='')),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('kcal_burned', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='fitness.tguser')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
