-- Vocab Bot — словарь из PDF Skyeng «1000 самых распространённых английских слов».
-- Извлечено vision-парсингом (в PDF нет текстового слоя). id = номер из PDF = порядок изучения.
-- Идемпотентно: повторный запуск обновит тексты, прогресс юзеров не тронет.
INSERT INTO vocab_word (id, word, ipa, translation, pos) VALUES
(1, 'Chill', 'tʃɪl', 'спокойный', NULL),
(2, 'Savage', '''sævɪdʒ', 'жесткий, брутальный', NULL),
(3, 'The party is lit', 'ðə ''pɑːti ɪz lɪt', 'вечеринка крутая', NULL),
(4, 'On fleek', 'ən ''fliːk', 'на высоте, просто отпад', NULL),
(5, 'Salty', '''sɔːlti, ''sɒlti', 'недовольный, обиженный', NULL),
(6, 'YOLO', '''jəʊləʊ', 'you only live once, лови момент', NULL),
(7, 'Vibe', 'vaɪb', 'вайб, атмосфера', NULL),
(8, 'Snatched', 'snætʃt', 'очень привлекательный', NULL),
(9, 'Cringe', 'krɪndʒ', 'кринж (ну, сами знаете)', NULL),
(10, 'Cram', 'kræm', 'интенсивно что-то делать', NULL),
(11, 'To crash', 'kræʃ', 'попадать в аварию; заявляться куда-то без приглашения', NULL),
(12, 'Dope!', 'dəʊp', 'Круто!', NULL),
(13, 'Yikes!', 'jaɪks', 'удивленное восклицание, что-то вроде «вау»', NULL),
(14, 'To flex', 'fleks', 'притворяться, понтоваться', NULL),
(15, 'Sus', 'sʌs', 'кто-то подозрительный', NULL),
(16, 'Fam', 'fæm', 'семья (сокр. от family), близкий друг/подруга', NULL),
(17, 'Snack', 'snæk', 'кто-то, кто привлекательно выглядит', NULL),
(18, 'Wig', 'wɪg', 'вау, круто', NULL),
(19, 'Hot', 'hɒt', 'привлекательный', NULL),
(20, 'Hypebeast', '''haɪp,biːst', 'тот, кто постоянно покупает лакшери-бренды', NULL),
(21, 'Corny', '''kɔːni', 'избитый, пошлый', NULL),
(22, 'Cheesy', '''tʃiːzi', 'банальный, дурацкий', NULL),
(23, 'Bussin''', '''bʌsɪn', 'крутой, на высоком уровне', NULL),
(24, 'Chocoholic', 'ˌtʃɒkə''hɒlɪk', '«шокоголик», сладкоежка', NULL),
(25, 'Workaholic', 'ˌwɜːkə''hɒlɪk', 'трудоголик', NULL),
(26, 'Shopaholic', 'ˌʃɒpə''hɒlɪk', 'шопоголик', NULL),
(27, 'Awesome', '''ɔːsəm', 'потрясающий', NULL),
(28, 'To screw up', '''skruː ʌp', 'налажать', NULL),
(29, 'Party animal', '''pɑːti ''ænɪml', 'любитель вечеринок', NULL),
(30, 'Smart cookie', 'smɑːt ''kʊki', 'умница', NULL),
(31, 'Early bird', '''ɜːli bɜːd', 'жаворонок (о человеке)', NULL),
(32, 'Creep', 'kriːp', 'очень неприятный, даже опасный человек', NULL),
(33, 'To humblebrag', '''hʌmblbræg', 'прибедняться (но на самом деле хвастаться)', NULL),
(34, 'Hustler', '''hʌslə(r)', 'пробивной человек', NULL),
(35, 'To troll', 'trɒl, trəʊl', 'троллить', NULL),
(36, 'Influencer', '''ɪnfluənsə(r)', 'инфлюенсер, человек с кучей подписчиков', NULL),
(37, 'Meme', 'miːm', 'мем', NULL),
(38, 'Drama queen', '''drɑːmə kwiːn', 'человек, который ведет себя слишком драматично для ситуации', NULL),
(39, 'Catfish', '''kætfɪʃ', 'онлайн-мошенник', NULL),
(40, 'The', 'ðiː, ði, ðə', 'определенный артикль', 'Артикли'),
(41, 'A (an)', 'eɪ, ə (æn, ən)', 'неопределенный артикль', 'Артикли'),
(42, 'To be', 'biː', 'быть', NULL),
(43, 'And', 'ænd', 'и', 'Союзы'),
(44, 'If', 'ɪf', 'если', 'Союзы'),
(45, 'Or', 'ɔː(r)', 'или', 'Союзы'),
(46, 'But', 'bʌt', 'но', 'Союзы'),
(47, 'Because', 'bɪ''kɒz', 'потому что', 'Союзы'),
(48, 'So', 'səʊ', 'поэтому', 'Союзы'),
(49, 'After', 'ɑːftə(r)', 'после того как', 'Союзы'),
(50, 'Before', 'bɪˈfɔː(r)', 'до того как', 'Союзы'),
(51, 'Than', 'ðæn', 'чем', 'Союзы'),
(52, 'Until', 'ənˈtɪl', 'до тех пор пока', 'Союзы'),
(53, 'To', 'tuː', 'к, в', 'Предлоги'),
(54, 'Of', 'ʌv', 'из, от, о', 'Предлоги'),
(55, 'In', 'ɪn', 'в', 'Предлоги'),
(56, 'For', 'fɔː(r)', 'для', 'Предлоги'),
(57, 'On', 'ɒn', 'на', 'Предлоги'),
(58, 'With', 'wɪð', 'с', 'Предлоги'),
(59, 'At', 'æt', 'в, на', 'Предлоги'),
(60, 'By', 'baɪ', 'к, по, от', 'Предлоги'),
(61, 'From', 'frɒm', 'из', 'Предлоги'),
(62, 'Into', 'ɪntuː', 'в, к', 'Предлоги'),
(63, 'Through', 'θruː', 'через', 'Предлоги'),
(64, 'Over', 'əʊvə(r)', 'над', 'Предлоги'),
(65, 'Inside', 'ˌɪnˈsaɪd', 'в, внутрь', 'Предлоги'),
(66, 'Above', 'əˈbʌv', 'над', 'Предлоги'),
(67, 'Across', 'əˈkrɒs', 'через', 'Предлоги'),
(68, 'Between', 'bɪˈtwiːn', 'между', 'Предлоги'),
(69, 'Near', 'nɪə(r)', 'возле', 'Предлоги'),
(70, 'Except', 'ɪkˈsept', 'кроме', 'Предлоги'),
(71, 'Despite', 'dɪˈspaɪt', 'несмотря на', 'Предлоги'),
(72, 'There', 'ðeə(r)', 'там', 'Наречия'),
(73, 'Better', 'betə(r)', 'лучше', 'Наречия'),
(74, 'Here', 'hɪə(r)', 'здесь', 'Наречия'),
(75, 'When', 'wen', 'когда', 'Наречия'),
(76, 'Where', 'weə(r)', 'где', 'Наречия'),
(77, 'As', 'æz', 'как', 'Наречия'),
(78, 'Out', 'aʊt', 'вне', 'Наречия'),
(79, 'Up', 'ʌp', 'вверх', 'Наречия'),
(80, 'Only', 'əʊnli', 'только', 'Наречия'),
(81, 'Then', 'ðen', 'тогда', 'Наречия'),
(82, 'How', 'haʊ', 'как', 'Наречия'),
(83, 'Lot', 'lɒt', 'много', 'Наречия'),
(84, 'Why', 'waɪ', 'почему', 'Наречия'),
(85, 'Already', 'ɔːlˈredi', 'уже', 'Наречия'),
(86, 'Yet', 'jet', 'еще', 'Наречия'),
(87, 'Yesterday', 'ˈjestədeɪ, ˈjestədi', 'вчера', 'Наречия'),
(88, 'Tomorrow', 'təˈmɒrəʊ', 'завтра', 'Наречия'),
(89, 'Today', 'təˈdeɪ', 'сегодня', 'Наречия'),
(90, 'Tonight', 'təˈnaɪt', 'сегодня вечером', 'Наречия'),
(91, 'Exactly', 'ɪgˈzæktli', 'точно', 'Наречия'),
(92, 'Back', 'bæk', 'назад', 'Наречия'),
(93, 'Still', 'stɪl', 'все еще', 'Наречия'),
(94, 'Too', 'tuː', 'слишком; тоже', 'Наречия'),
(95, 'Down', 'daʊn', 'вниз', 'Наречия'),
(96, 'Simply', 'ˈsɪmpli', 'просто', 'Наречия'),
(97, 'Less', 'les', 'меньше', 'Наречия'),
(98, 'Beyond', 'bɪˈjɒnd', 'вне', 'Наречия'),
(99, 'Rather', 'ˈrɑːðə(r)', 'довольно', 'Наречия'),
(100, 'Suddenly', 'ˈsʌdənli', 'вдруг', 'Наречия'),
(101, 'Obviously', 'ˈɒbviəsli', 'очевидно', 'Наречия'),
(102, 'Also', 'ˈɔːlsəʊ', 'тоже', 'Наречия'),
(103, 'Well', 'wel', 'хорошо', 'Наречия'),
(104, 'Soon', 'suːn', 'скоро', 'Наречия'),
(105, 'Again', 'əˈgen, əˈgeɪn', 'снова', 'Наречия'),
(106, 'Almost', 'ˈɔːlməʊst', 'почти', 'Наречия'),
(107, 'Always', 'ˈɔːlweɪz', 'всегда', 'Наречия'),
(108, 'Sometimes', 'ˈsʌmtaɪmz', 'иногда', 'Наречия'),
(109, 'Else', 'els', 'еще', 'Наречия'),
(110, 'Enough', 'ɪˈnʌf', 'достаточно', 'Наречия'),
(111, 'Ever', 'ˈevər', 'когда-либо', 'Наречия'),
(112, 'Never', 'ˈnevər', 'никогда', 'Наречия'),
(113, 'Far', 'fɑː(r)', 'далеко', 'Наречия'),
(114, 'Really', 'ˈriːəli', 'на самом деле', 'Наречия'),
(115, 'Ago', 'əˈgəʊ', 'тому назад', 'Наречия'),
(116, 'Finally', 'ˈfaɪnəli', 'наконец', 'Наречия'),
(117, 'Instead', 'ɪnˈsted', 'вместо', 'Наречия'),
(118, 'Likely', 'ˈlaɪkli', 'вероятно', 'Наречия'),
(119, 'Maybe', 'ˈmeɪbi', 'возможно', 'Наречия'),
(120, 'Very', 'ˈveri', 'очень', 'Наречия'),
(121, 'Once', 'wʌns', 'однажды', 'Наречия'),
(122, 'All', 'ɔːl', 'все', 'Местоимения'),
(123, 'That', 'ðæt', 'который, тот', 'Местоимения'),
(124, 'I', 'aɪ', 'я', 'Местоимения'),
(125, 'Any', 'ˈeni', 'любой', 'Местоимения'),
(126, 'It', 'ɪt', 'оно', 'Местоимения'),
(127, 'He', 'hi', 'он', 'Местоимения'),
(128, 'You', 'juː', 'ты', 'Местоимения'),
(129, 'This', 'ðɪs', 'этот', 'Местоимения'),
(130, 'My', 'maɪ', 'мой', 'Местоимения'),
(131, 'Him', 'hɪm', 'его (знаю кого?)', 'Местоимения'),
(132, 'Your', 'jɔː(r)', 'твой', 'Местоимения'),
(133, 'Some', 'sʌm', 'некоторый', 'Местоимения'),
(134, 'Me', 'miː', 'я, мне', 'Местоимения'),
(135, 'Our', 'ˈaʊə(r), ɑː(r)', 'наш', 'Местоимения'),
(136, 'Her', 'hɜː(r)', 'ее (знаю кого?)', 'Местоимения'),
(137, 'These', 'ðiːz', 'эти', 'Местоимения'),
(138, 'Us', 'ʌs', 'нас', 'Местоимения'),
(139, 'Their', 'ðeə(r)', 'их (чье?)', 'Местоимения'),
(140, 'She', 'ʃiː', 'она', 'Местоимения'),
(141, 'We', 'wiː', 'мы', 'Местоимения'),
(142, 'They', 'ðeɪ', 'они', 'Местоимения'),
(143, 'His', 'hɪz, ɪz', 'его (чей?)', 'Местоимения'),
(144, 'Its', 'ɪts', 'его (чей?) (о неодушевленных предметах)', 'Местоимения'),
(145, 'Them', 'ðəm', 'их (кого?)', 'Местоимения'),
(146, 'Who', 'huː', 'кто', 'Местоимения'),
(147, 'Which', 'wɪtʃ', 'который', 'Местоимения'),
(148, 'Someone', 'ˈsʌmwʌn', 'кто-то', 'Местоимения'),
(149, 'Somebody', 'ˈsʌmbədi', 'кто-нибудь', 'Местоимения'),
(150, 'Everything', 'ˈevriθɪŋ', 'всё', 'Местоимения'),
(151, 'Man', 'mæn', 'человек, мужчина', NULL),
(152, 'Woman', 'ˈwʊmən', 'женщина', NULL),
(153, 'Time', 'taɪm', 'время', NULL),
(154, 'State', 'steɪt', 'состояние; государство, штат', NULL),
(155, 'Year', 'jɪə(r), jɜː(r)', 'год', NULL),
(156, 'People', 'ˈpiːpl', 'люди', NULL),
(157, 'Work', 'wɜːk', 'работа', NULL),
(158, 'Age', 'eɪdʒ', 'возраст', NULL),
(159, 'Day', 'deɪ', 'день', NULL),
(160, 'Name', 'neɪm', 'имя', NULL),
(161, 'Light', 'laɪt', 'свет', NULL),
(162, 'Information', 'ˌɪnfəˈmeɪʃn', 'информация', NULL),
(163, 'Education', 'ˌedʒuˈkeɪʃn', 'образование', NULL),
(164, 'Force', 'fɔːs', 'сила', NULL),
(165, 'Teacher', 'ˈtiːtʃə(r)', 'учитель', NULL),
(166, 'Air', 'eə(r)', 'воздух', NULL),
(167, 'Moment', 'ˈməʊmənt', 'момент', NULL),
(168, 'Guy', 'gaɪ', 'парень', NULL),
(169, 'Girl', 'gɜːl', 'девочка, девушка', NULL),
(170, 'Research', 'rɪˈsɜːtʃ, ˈriːsɜːtʃ', 'исследование', NULL),
(171, 'List', 'lɪst', 'список', NULL),
(172, 'Reason', 'ˈriːzn', 'причина', NULL),
(173, 'Morning', 'ˈmɔːnɪŋ', 'утро', NULL),
(174, 'Result', 'rɪˈzʌlt', 'результат', NULL),
(175, 'Party', 'ˈpɑːti', 'вечеринка', NULL),
(176, 'History', 'ˈhɪstri', 'история (наука)', NULL),
(177, 'War', 'wɔː(r)', 'война', NULL),
(178, 'Art', 'ɑːt', 'искусство', NULL),
(179, 'Person', 'ˈpɜːsn', 'человек, персона', NULL),
(180, 'Health', 'helθ', 'здоровье', NULL),
(181, 'Window', 'ˈwɪndəʊ', 'окно', NULL),
(182, 'Door', 'dɔː(r)', 'дверь', NULL),
(183, 'Office', 'ˈɒfɪs', 'офис', NULL),
(184, 'Level', 'ˈlevl', 'уровень', NULL),
(185, 'Face', 'feɪs', 'лицо', NULL),
(186, 'Parent', 'ˈpeərənt', 'родитель', NULL),
(187, 'Body', 'ˈbɒdi', 'тело', NULL),
(188, 'Kid', 'kɪd', 'ребенок', NULL),
(189, 'Century', 'ˈsentʃəri', 'век', NULL),
(190, 'Evidence', 'ˈevɪdəns', 'доказательство', NULL),
(191, 'Chance', 'tʃɑːns', 'шанс', NULL),
(192, 'Period', 'ˈpɪəriəd', 'период', NULL),
(193, 'Future', 'ˈfjuːtʃə(r)', 'будущее', NULL),
(194, 'Behaviour', 'bɪˈheɪvjə(r)', 'поведение', NULL),
(195, 'Performance', 'pəˈfɔːməns', 'выступление', NULL),
(196, 'Blood', 'blʌd', 'кровь', NULL),
(197, 'Colour', 'ˈkʌlə(r)', 'цвет', NULL),
(198, 'Idea', 'aɪˈdɪə', 'идея', NULL),
(199, 'Minute', 'ˈmɪnɪt', 'минута', NULL),
(200, 'Team', 'tiːm', 'команда', NULL),
(201, 'Comfort', 'ˈkʌmfət', 'комфорт', NULL),
(202, 'President', 'ˈprezɪdənt', 'президент', NULL),
(203, 'Eye', 'aɪ', 'глаз', NULL),
(204, 'Book', 'bʊk', 'книга', NULL),
(205, 'Month', 'mʌnθ', 'месяц', NULL),
(206, 'Number', 'ˈnʌmbə(r)', 'номер', NULL),
(207, 'Store', 'stɔː(r)', 'магазин', NULL),
(208, 'Movement', 'ˈmuːvmənt', 'движение', NULL),
(209, 'Decade', 'ˈdekeɪd, dɪˈkeɪd', 'десятилетие', NULL),
(210, 'Treatment', 'ˈtriːtmənt', 'уход, отношение', NULL),
(211, 'Dream', 'driːm', 'мечта', NULL),
(212, 'Middle', 'ˈmɪdl', 'середина', NULL),
(213, 'Trouble', 'ˈtrʌbl', 'проблема, неприятность', NULL),
(214, 'Pain', 'peɪn', 'боль', NULL),
(215, 'Peace', 'piːs', 'мир, покой', NULL),
(216, 'Fact', 'fækt', 'факт', NULL),
(217, 'Story', 'ˈstɔːri', 'рассказ', NULL),
(218, 'Money', 'ˈmʌni', 'деньги', NULL),
(219, 'Area', 'ˈeəriə', 'место, зона', NULL),
(220, 'Mother', 'ˈmʌðə(r)', 'мать', NULL),
(221, 'Room', 'ruːm, rʊm', 'комната, номер', NULL),
(222, 'Water', 'ˈwɔːtə(r)', 'вода', NULL),
(223, 'Home', 'həʊm', 'дом', NULL),
(224, 'Point', 'pɔɪnt', 'точка', NULL),
(225, 'Night', 'naɪt', 'ночь', NULL),
(226, 'Type', 'taɪp', 'тип', NULL),
(227, 'Nation', 'ˈneɪʃn', 'нация', NULL),
(228, 'Heart', 'hɑːt', 'сердце', NULL),
(229, 'Value', 'ˈvæljuː', 'ценность, значение', NULL),
(230, 'Report', 'rɪˈpɔːt', 'отчет', NULL),
(231, 'Government', 'ˈgʌvənmənt', 'правительство', NULL),
(232, 'Question', 'ˈkwestʃən', 'вопрос', NULL),
(233, 'Way', 'weɪ', 'путь', NULL),
(234, 'System', 'ˈsɪstəm', 'система', NULL),
(235, 'Company', 'ˈkʌmpəni', 'компания', NULL),
(236, 'Case', 'keɪs', 'случай', NULL),
(237, 'Place', 'pleɪs', 'место', NULL),
(238, 'Hand', 'hænd', 'кисть руки', NULL),
(239, 'Country', 'ˈkʌntri', 'страна', NULL),
(240, 'Group', 'gruːp', 'группа', NULL),
(241, 'World', 'wɜːld', 'мир, вселенная', NULL),
(242, 'Life', 'laɪf', 'жизнь', NULL),
(243, 'Daughter', 'ˈdɔːtə(r)', 'дочь', NULL),
(244, 'Son', 'sʌn', 'сын', NULL),
(245, 'Grandma', 'ˈgrænmɑː', 'бабушка', NULL),
(246, 'Brother', 'ˈbrʌðə(r)', 'брат', NULL),
(247, 'Sister', 'ˈsɪstə(r)', 'сестра', NULL),
(248, 'Grandpa', 'ˈgrænpɑː', 'дедушка', NULL),
(249, 'Dad', 'dæd', 'папа', NULL),
(250, 'Mum', 'mʌm', 'мама', NULL),
(251, 'Autumn', 'ˈɔːtəm', 'осень', NULL),
(252, 'Spring', 'sprɪŋ', 'весна', NULL),
(253, 'Winter', 'ˈwɪntə(r)', 'зима', NULL),
(254, 'Summer', 'ˈsʌmə(r)', 'лето', NULL),
(255, 'End', 'end', 'конец', NULL),
(256, 'Line', 'laɪn', 'очередь; линия', NULL),
(257, 'Power', 'ˈpaʊə(r)', 'сила', NULL),
(258, 'Father', 'ˈfɑːðə(r)', 'отец', NULL),
(259, 'Weapon', 'ˈwepən', 'оружие', NULL),
(260, 'Stuff', 'stʌf', 'вещи', NULL),
(261, 'Range', 'reɪndʒ', 'ряд, диапазон', NULL),
(262, 'Weight', 'weɪt', 'вес', NULL),
(263, 'Service', 'ˈsɜːvɪs', 'услуга, сервис', NULL),
(264, 'House', 'haʊs', 'дом', NULL),
(265, 'Measure', 'ˈmeʒə(r)', 'мера, степень', NULL),
(266, 'Head', 'hed', 'голова', NULL),
(267, 'Side', 'saɪd', 'сторона', NULL),
(268, 'Business', 'ˈbɪznəs', 'бизнес, дело', NULL),
(269, 'Pharmacy', 'ˈfɑːməsi', 'аптека', NULL),
(270, 'Lyrics', 'ˈlɪrɪks', 'текст песни', NULL),
(271, 'Verse', 'vɜːs', 'стих', NULL),
(272, 'Record', 'ˈrekɔːd', 'запись', NULL),
(273, 'Rhythm', 'ˈrɪðəm', 'ритм', NULL),
(274, 'Job', 'dʒɒb', 'работа, занятие', NULL),
(275, 'Order', 'ˈɔːdə(r)', 'заказ', NULL),
(276, 'Genre', 'ˈʒɒnrə', 'жанр', NULL),
(277, 'Flat', 'flæt', 'квартира', NULL),
(278, 'Theory', 'ˈθɪəri', 'теория', NULL),
(279, 'Trainers', 'ˈtreɪnəz', 'кроссовки, спортивная обувь', NULL),
(280, 'Base', 'beɪs', 'база', NULL),
(281, 'Pack', 'pæk', 'упаковка', NULL),
(282, 'Bumbag', 'ˈbʌmbæg', 'поясная сумка', NULL),
(283, 'Trousers', 'ˈtraʊzəz', 'брюки', NULL),
(284, 'Eraser', 'ɪˈreɪzə(r)', 'ластик', NULL),
(285, 'Box', 'bɒks', 'коробка', NULL),
(286, 'Knowledge', 'ˈnɒlɪdʒ', 'знание', NULL),
(287, 'Thing', 'θɪŋ', 'вещь', NULL),
(288, 'School', 'skuːl', 'школа', NULL),
(289, 'Problem', 'ˈprɒbləm', 'проблема', NULL),
(290, 'Student', 'ˈstjuːdnt', 'студент', NULL),
(291, 'Truth', 'truːθ', 'правда', NULL),
(292, 'Food', 'fuːd', 'еда', NULL),
(293, 'City', 'ˈsɪti', 'город', NULL),
(294, 'To sip', 'sɪp', 'потягивать (напиток)', NULL),
(295, 'To drink', 'drɪŋk', 'пить', NULL),
(296, 'Savoury', 'ˈseɪvəri', 'пикантный', NULL),
(297, 'Aperitif', 'əˌperəˈtiːf', 'аперитив', NULL),
(298, 'Beverage', 'ˈbevərɪdʒ', 'напиток', NULL),
(299, 'Bitter', 'ˈbɪtə(r)', 'горький', NULL),
(300, 'Acerb', 'əˈsɜːb', 'терпкий', NULL),
(301, 'Sourness', 'ˈsaʊənəs', 'кислинка', NULL),
(302, 'Tasting', 'ˈteɪstɪŋ', 'дегустация', NULL),
(303, 'Glass', 'glɑːs', 'стакан', NULL),
(304, 'Flight', 'flaɪt', 'перелет; рейс', NULL),
(305, 'To check in', 'tʃek ɪn', 'зарегистрироваться', NULL),
(306, 'To explore', 'ɪkˈsplɔː(r)', 'исследовать', NULL),
(307, 'Boarding', 'ˈbɔːdɪŋ', 'посадка', NULL),
(308, 'Suitcase', 'ˈsuːtkeɪs', 'чемодан', NULL),
(309, 'Bag', 'bæg', 'сумка', NULL),
(310, 'Itinerary', 'aɪˈtɪnərəri', 'маршрут', NULL),
(311, 'To navigate', 'ˈnævɪgeɪt', 'ориентироваться, перемещаться', NULL),
(312, 'Vacation', 'veɪˈkeɪʃn, vəˈkeɪʃn', 'отпуск', NULL),
(313, 'Wanderlust', 'ˈwɒndəlʌst', 'страсть к путешествиям', NULL),
(314, 'Driver', 'ˈdraɪvə(r)', 'водитель', NULL),
(315, 'Accommodation', 'əˌkɒməˈdeɪʃn', 'жилье, размещение', NULL),
(316, 'Hotel', 'həʊˈtel', 'отель', NULL),
(317, 'Hostel', 'ˈhɒstl', 'хостел, гостиница', NULL),
(318, 'Airbnb', 'ˌeə biː en ˈbiː', 'сами знаете', NULL),
(319, 'Visa', 'ˈviːzə', 'виза', NULL),
(320, 'Passport control', 'ˌpɑːspɔːt kənˈtrəʊl', 'паспортный контроль', NULL),
(321, 'Immigration', 'ˌɪmɪˈgreɪʃn', 'иммиграция', NULL),
(322, 'Bus', 'bʌs', 'автобус', NULL),
(323, 'To take off', 'ˈteɪk ɒf', 'отправляться', NULL),
(324, 'Airport', 'ˈeəpɔːt', 'аэропорт', NULL),
(325, 'Terminal', 'ˈtɜːmɪnl', 'терминал', NULL),
(326, 'Ticket', 'ˈtɪkɪt', 'билет', NULL),
(327, 'Luggage', 'ˈlʌgɪdʒ', 'багаж', NULL),
(328, 'Departure', 'dɪˈpɑːtʃə(r)', 'отправление', NULL),
(329, 'Stopover', 'ˈstɒpəʊvə(r)', 'остановка', NULL),
(330, 'Transit', 'ˈtrænzɪt', 'транзит, прохождение', NULL),
(331, 'Cruise', 'kruːz', 'круиз', NULL),
(332, 'Ship', 'ʃɪp', 'корабль', NULL),
(333, 'Ferry', 'ˈferi', 'паром', NULL),
(334, 'To rent', 'rent', 'арендовать', NULL),
(335, 'Uber', 'uːbə(r)', 'и это вы знаете', NULL),
(336, 'To move', 'muːv', 'двигаться', NULL),
(337, 'To come', 'kʌm', 'идти', NULL),
(338, 'Underground', 'ˌʌndəˈgraʊnd', 'метро', NULL),
(339, 'View', 'vjuː', 'вид', NULL),
(340, 'Bicycle', 'ˈbaɪsɪkl', 'велосипед', NULL),
(341, 'Sightseeing', 'ˈsaɪtsiːɪŋ', 'осмотр достопримечательностей', NULL),
(342, 'Landmark', 'ˈlændmɑːk', 'ориентир, знак', NULL),
(343, 'Museum', 'mjuˈziːəm', 'музей', NULL),
(344, 'Gallery', 'ˈgæləri', 'галерея', NULL),
(345, 'Bank', 'bæŋk', 'банк', NULL),
(346, 'Building', 'ˈbɪldɪŋ', 'здание', NULL),
(347, 'Beach', 'biːtʃ', 'пляж', NULL),
(348, 'Stop', 'stɒp', 'остановка', NULL),
(349, 'To request', 'rɪˈkwest', 'просить', NULL),
(350, 'To delay', 'dɪˈleɪ', 'задерживаться', NULL),
(351, 'To book', 'bʊk', 'бронировать', NULL),
(352, 'To land', 'lænd', 'приземляться', NULL),
(353, 'International', 'ˌɪntəˈnæʃnəl', 'международный', NULL),
(354, 'Transfer', 'ˈtrænsfɜː(r)', 'пересадка', NULL),
(355, 'Reclaim', 'rɪˈkleɪm', 'выдача (багажа)', NULL),
(356, 'To expect', 'ɪkˈspekt', 'ожидать', NULL),
(357, 'Tourist', 'ˈtʊərɪst, ˈtɔːrɪst', 'турист', NULL),
(358, 'Passenger', 'ˈpæsɪndʒə(r)', 'пассажир', NULL),
(359, 'Stairs', 'steəz', 'лестница', NULL),
(360, 'Cinema', 'ˈsɪnəmə, ˈsɪnəmɑː', 'кинотеатр', NULL),
(361, 'To wave', 'weɪv', 'махать', NULL),
(362, 'Gate', 'geɪt', 'выход на посадку', NULL),
(363, 'Train', 'treɪn', 'поезд', NULL),
(364, 'Exploration', 'ˌekspləˈreɪʃn', 'исследование', NULL),
(365, 'Mountain', 'ˈmaʊntən', 'гора', NULL),
(366, 'Hiking', 'ˈhaɪkɪŋ', 'пешие прогулки', NULL),
(367, 'Trekking', 'ˈtrekɪŋ', 'походы', NULL),
(368, 'Diving', 'ˈdaɪvɪŋ', 'дайвинг', NULL),
(369, 'Surfing', 'ˈsɜːfɪŋ', 'серфинг', NULL),
(370, 'Skiing', 'ˈskiːɪŋ', 'лыжный спорт', NULL),
(371, 'Wonderful', 'ˈwʌndəfl', 'замечательный', NULL),
(372, 'Cuisine', 'kwɪˈziːn', 'кулинария, кухня', NULL),
(373, 'Taxi', 'ˈtæksi', 'такси', NULL),
(374, 'Seat', 'siːt', 'место', NULL),
(375, 'Restaurant', 'ˈrestrɒnt', 'ресторан', NULL),
(376, 'Street food', 'ˈstriːt fuːd', 'уличная еда', NULL),
(377, 'Market', 'ˈmɑːkɪt', 'рынок', NULL),
(378, 'Shopping', 'ˈʃɒpɪŋ', 'шопинг', NULL),
(379, 'Souvenir', 'ˌsuːvəˈnɪə(r)', 'сувенир', NULL),
(380, 'Currency', 'ˈkʌrənsi', 'валюта', NULL),
(381, 'Exchange', 'ɪksˈtʃeɪndʒ', 'обмен', NULL),
(382, 'ATM', 'ˌeɪ tiː ˈem', 'банкомат', NULL),
(383, 'Budget', 'ˈbʌdʒɪt', 'бюджет', NULL),
(384, 'Expense', 'ɪkˈspens', 'расходы', NULL),
(385, 'Insurance', 'ɪnˈʃʊərəns, ɪnˈʃɔːrəns', 'страховка', NULL),
(386, 'Safety', 'ˈseɪfti', 'безопасность', NULL),
(387, 'Vaccination', 'ˌvæksɪˈneɪʃn', 'вакцинация', NULL),
(388, 'Culture', 'ˈkʌltʃə(r)', 'культура', NULL),
(389, 'Local', 'ˈləʊkl', 'местный', NULL),
(390, 'Guide', 'gaɪd', 'экскурсовод; гайд', NULL),
(391, 'Map', 'mæp', 'карта', NULL),
(392, 'GPS', 'ˌdʒiː piː ˈes', 'GPS-навигатор', NULL),
(393, 'Tour', 'tʊə(r), tɔː(r)', 'тур', NULL),
(394, 'Package', 'ˈpækɪdʒ', 'посылка', NULL),
(395, 'Festival', 'ˈfestɪvl', 'фестиваль', NULL),
(396, 'Season', 'ˈsiːzn', 'сезон; время года', NULL),
(397, 'Climate', 'ˈklaɪmət', 'климат', NULL),
(398, 'Tropical', 'ˈtrɒpɪkl', 'тропический', NULL),
(399, 'Sunscreen', 'ˈsʌnskriːn', 'солнцезащитный крем', NULL),
(400, 'Backpacking', 'ˈbækpækɪŋ', 'путешествия налегке (с рюкзаком)', NULL),
(401, 'Camping', 'ˈkæmpɪŋ', 'кемпинг; отдых в палатке', NULL),
(402, 'Wildlife', 'ˈwaɪldlaɪf', 'дикая природа', NULL),
(403, 'Nature', 'ˈneɪtʃə(r)', 'природа', NULL),
(404, 'Bed and breakfast', 'bed ən ˈbrekfəst', 'гостиница с ночлегом и завтраком', NULL),
(405, 'Adventure', 'ədˈventʃə(r)', 'приключение', NULL),
(406, 'National park', 'ˈnæʃnəl ˈpɑːk', 'национальный парк', NULL),
(407, 'Heritage', 'ˈherɪtɪdʒ', 'наследие', NULL),
(408, 'To arrive', 'əˈraɪv', 'прибывать', NULL),
(409, 'Architecture', 'ˈɑːkɪtektʃə(r)', 'архитектура', NULL),
(410, 'Ruins', 'ˈruːɪnz', 'руины', NULL),
(411, 'Temple', 'ˈtempl', 'храм', NULL),
(412, 'Church', 'tʃɜːtʃ', 'церковь', NULL),
(413, 'Mosque', 'mɒsk', 'мечеть', NULL),
(414, 'Monument', 'ˈmɒnjumənt', 'памятник', NULL),
(415, 'Photography', 'fəˈtɒgrəfi', 'фотография (как занятие)', NULL),
(416, 'Memory', 'ˈmeməri', 'память', NULL),
(417, 'Experience', 'ɪkˈspɪəriəns', 'опыт', NULL),
(418, 'Escape', 'ɪˈskeɪp', 'побег', NULL),
(419, 'Customs', 'ˈkʌstəmz', 'таможня', NULL),
(420, 'Reservation', 'ˌrezəˈveɪʃn', 'бронирование', NULL),
(421, 'Shower', 'ˈʃaʊə(r)', 'душ', NULL),
(422, 'Suite', 'swiːt', 'номер люкс', NULL),
(423, 'Key', 'kiː', 'ключ', NULL),
(424, 'Receipt', 'rɪˈsiːt', 'чек', NULL),
(425, 'Hairdryer', 'ˈheədraɪə(r)', 'фен', NULL),
(426, 'Battery', 'ˈbætri, ˈbætəri', 'аккумулятор', NULL),
(427, 'Part', 'pɑːt', 'часть', NULL),
(428, 'Police', 'pəˈliːs', 'полиция', NULL),
(429, 'Station', 'ˈsteɪʃn', 'станция', NULL),
(430, 'Price', 'praɪs', 'цена', NULL),
(431, 'Resort', 'rɪˈzɔːt', 'курорт', NULL),
(432, 'Breakfast', 'ˈbrekfəst', 'завтрак', NULL),
(433, 'Air conditioner', 'ˈeə kəndɪʃənə(r)', 'кондиционер', NULL),
(434, 'Bath', 'bɑːθ', 'ванна', NULL),
(435, 'Towel', 'ˈtaʊəl', 'полотенце', NULL),
(436, 'Tip', 'tɪp', 'чаевые', NULL),
(437, 'Cash', 'kæʃ', 'наличные', NULL),
(438, 'Rate', 'reɪt', 'стоимость, курс валюты', NULL),
(439, 'Electrical', 'ɪˈlektrɪkl', 'электрический', NULL),
(440, 'Successful', 'səkˈsesfl', 'успешный', NULL),
(441, 'Significant', 'sɪgˈnɪfɪkənt', 'значительный', NULL),
(442, 'Former', 'ˈfɔːmə(r)', 'бывший', NULL),
(443, 'Sick', 'sɪk', 'больной', NULL),
(444, 'Ready', 'ˈredi', 'готовый', NULL),
(445, 'Bored', 'bɔːd', 'скучающий', NULL),
(446, 'Traditional', 'trəˈdɪʃnl', 'традиционный', NULL),
(447, 'Medical', 'ˈmedɪkl', 'медицинский', NULL),
(448, 'Financial', 'faɪˈnænʃl, fəˈnænʃl', 'финансовый', NULL),
(449, 'Major', 'ˈmeɪdʒə(r)', 'основной', NULL),
(450, 'Expensive', 'ɪkˈspensɪv', 'дорогой', NULL),
(451, 'Slow', 'sləʊ', 'медленный', NULL),
(452, 'Similar', 'ˈsɪmələ(r)', 'похожий', NULL),
(453, 'Weird', 'wɪəd', 'странный', NULL),
(454, 'Good', 'gʊd', 'хороший', NULL),
(455, 'Curious', 'ˈkjʊəriəs', 'любопытный', NULL),
(456, 'Cool', 'kuːl', 'крутой', NULL),
(457, 'Additional', 'əˈdɪʃnl', 'дополнительный', NULL),
(458, 'Mental', 'ˈmentl', 'ментальный', NULL),
(459, 'Useful', 'ˈjuːsfl', 'полезный', NULL),
(460, 'Late', 'leɪt', 'поздний', NULL),
(461, 'Shocked', 'ʃɒkt', 'потрясенный', NULL),
(462, 'Excited', 'ɪkˈsaɪtɪd', 'взволнованный, но в хорошем смысле', NULL),
(463, 'Difficult', 'ˈdɪfɪkəlt', 'сложный', NULL),
(464, 'Fresh', 'freʃ', 'свежий', NULL),
(465, 'Different', 'ˈdɪfrənt', 'другой, разный', NULL),
(466, 'Favourite', 'ˈfeɪvərɪt', 'любимый', NULL),
(467, 'Available', 'əˈveɪləbl', 'доступный', NULL),
(468, 'Possible', 'ˈpɒsəbl', 'возможный', NULL),
(469, 'Physical', 'ˈfɪzɪkl', 'физический', NULL),
(470, 'Casual', 'ˈkæʒuəl', 'повседневный', NULL),
(471, 'Happy', 'ˈhæpi', 'счастливый', NULL),
(472, 'Correct', 'kəˈrekt', 'правильный', NULL),
(473, 'Personal', 'ˈpɜːsənl', 'личный', NULL),
(474, 'Serious', 'ˈsɪəriəs', 'серьезный', NULL),
(475, 'Visible', 'ˈvɪzəbl', 'видимый', NULL),
(476, 'Short', 'ʃɔːt', 'короткий', NULL),
(477, 'Right', 'raɪt', 'правый, правильный', NULL),
(478, 'Bad', 'bæd', 'плохой', NULL),
(479, 'Nice', 'naɪs', 'хороший', NULL),
(480, 'Large', 'lɑːdʒ', 'очень большой', NULL),
(481, 'Black', 'blæk', 'черный', NULL),
(482, 'White', 'waɪt', 'белый', NULL),
(483, 'Leather', 'ˈleðə(r)', 'кожаный', NULL),
(484, 'Rare', 'reə(r)', 'редкий', NULL),
(485, 'Wooden', 'ˈwʊdn', 'деревянный', NULL),
(486, 'Wide', 'waɪd', 'широкий', NULL),
(487, 'Warm', 'wɔːm', 'теплый', NULL),
(488, 'Wrong', 'rɒŋ', 'неверный', NULL),
(489, 'Common', 'ˈkɒmən', 'общий', NULL),
(490, 'Sweet', 'swiːt', 'сладкий', NULL),
(491, 'Safe', 'seɪf', 'безопасный', NULL),
(492, 'Round', 'raʊnd', 'круглый', NULL),
(493, 'Rich', 'rɪtʃ', 'богатый', NULL),
(494, 'Natural', 'ˈnætʃrəl', 'натуральный', NULL),
(495, 'Red', 'red', 'красный', NULL),
(496, 'Quick', 'kwɪk', 'быстрый', NULL),
(497, 'Loud', 'laʊd', 'громкий', NULL),
(498, 'Lonely', 'ˈləʊnli', 'одинокий', NULL),
(499, 'Long', 'lɒŋ', 'долгий, длинный', NULL),
(500, 'Poor', 'pɔː(r), pʊə(r)', 'бедный', NULL),
(501, 'Heavy', 'ˈhevi', 'тяжелый', NULL),
(502, 'Green', 'griːn', 'зеленый', NULL),
(503, 'Full', 'fʊl', 'полный', NULL),
(504, 'Empty', 'ˈempti', 'пустой', NULL),
(505, 'Deep', 'diːp', 'глубокий', NULL),
(506, 'Cold', 'kəʊld', 'холодный', NULL),
(507, 'Lost', 'lɒst', 'потерянный', NULL),
(508, 'Brown', 'braʊn', 'коричневый', NULL),
(509, 'Blue', 'bluː', 'синий', NULL),
(510, 'Recent', 'ˈriːsnt', 'недавний', NULL),
(511, 'Actual', 'ˈæktʃuəl', 'актуальный, действительный', NULL),
(512, 'Strong', 'strɒŋ', 'сильный', NULL),
(513, 'Basic', 'ˈbeɪsɪk', 'базовый', NULL),
(514, 'Important', 'ɪmˈpɔːtnt', 'важный', NULL),
(515, 'Serious', 'ˈsɪəriəs', 'серьезный', NULL),
(516, 'Known', 'nəʊn', 'известный', NULL),
(517, 'Huge', 'hjuːdʒ', 'огромный', NULL),
(518, 'Decent', 'ˈdiːsnt', 'приличный', NULL),
(519, 'Fun', 'fʌn', 'веселый', NULL),
(520, 'United', 'juˈnaɪtɪd', 'объединенный', NULL),
(521, 'Several', 'ˈsevrəl', 'некоторый', NULL),
(522, 'Certain', 'ˈsɜːtn', 'определенный', NULL),
(523, 'Necessary', 'ˈnesəsəri', 'необходимый', NULL),
(524, 'Best', 'best', 'лучший', NULL),
(525, 'Particular', 'pəˈtɪkjələ(r)', 'конкретный', NULL),
(526, 'Entire', 'ɪnˈtaɪə(r)', 'целый', NULL),
(527, 'Various', 'ˈveəriəs', 'разнообразный', NULL),
(528, 'Ugly', 'ˈʌgli', 'уродливый', NULL),
(529, 'Accurate', 'ˈækjərət', 'точный', NULL),
(530, 'Great', 'greɪt', 'отличный', NULL),
(531, 'Beautiful', 'ˈbjuːtɪfl', 'красивый', NULL),
(532, 'Small', 'smɔːl', 'маленький', NULL),
(533, 'Dark', 'dɑːk', 'темный', NULL),
(534, 'Calm', 'kɑːm', 'спокойный', NULL),
(535, 'Relevant', 'ˈreləvənt', 'соответствующий, уместный', NULL),
(536, 'Surprised', 'səˈpraɪzd', 'удивленный', NULL),
(537, 'Impossible', 'ɪmˈpɒsəbl', 'невозможный', NULL),
(538, 'Freezing', 'ˈfriːzɪŋ', 'ледяной', NULL),
(539, 'Warming', 'ˈwɔːmɪŋ', 'согревающий', NULL),
(540, 'Other', 'ˈʌðə(r)', 'другой', NULL),
(541, 'Many', 'ˈmeni', 'многий', NULL),
(542, 'Same', 'seɪm', 'такой же, аналогичный', NULL),
(543, 'New', 'njuː', 'новый', NULL),
(544, 'First', 'fɜːst', 'первый', NULL),
(545, 'Last', 'lɑːst', 'последний', NULL),
(546, 'Little', 'ˈlɪtl', 'маленький', NULL),
(547, 'Own', 'əʊn', 'собственный', NULL),
(548, 'Old', 'əʊld', 'старый', NULL),
(549, 'Big', 'bɪg', 'большой', NULL),
(550, 'Next', 'nekst', 'следующий', NULL),
(551, 'Young', 'jʌŋ', 'молодой', NULL),
(552, 'Public', 'ˈpʌblɪk', 'общественный', NULL),
(553, 'Bright', 'braɪt', 'яркий', NULL),
(554, 'Fast', 'fɑːst', 'быстрый', NULL),
(555, 'Easy', 'ˈiːzi', 'легкий', NULL),
(556, 'Busy', 'ˈbɪzi', 'занятой', NULL),
(557, 'Dangerous', 'ˈdeɪndʒərəs', 'опасный', NULL),
(558, 'Clean', 'kliːn', 'чистый', NULL),
(559, 'Quiet', 'ˈkwaɪət', 'тихий', NULL),
(560, 'Charming', 'ˈtʃɑːmɪŋ', 'очаровательный', NULL),
(561, 'Confident', 'ˈkɒnfɪdənt', 'уверенный', NULL),
(562, 'Willing', 'ˈwɪlɪŋ', 'желающий что-то сделать', 'Прилагательные'),
(563, 'Helpful', 'ˈhelpfl', 'отзывчивый', 'Прилагательные'),
(564, 'Terrible', 'ˈterəbl', 'ужасный', 'Прилагательные'),
(565, 'Interesting', 'ˈɪntrəstɪŋ, ˈɪntrestɪŋ', 'интересный', 'Прилагательные'),
(566, 'Responsible', 'rɪˈspɒnsəbl', 'ответственный', 'Прилагательные'),
(567, 'Pregnant', 'ˈpregnənt', 'беременный', 'Прилагательные'),
(568, 'Healthy', 'ˈhelθi', 'здоровый', 'Прилагательные'),
(569, 'Political', 'pəˈlɪtɪkl', 'политически активный', 'Прилагательные'),
(570, 'Emotional', 'ɪˈməʊʃənl', 'эмоциональный', 'Прилагательные'),
(571, 'Scared', 'skeəd', 'испуганный', 'Прилагательные'),
(572, 'Mad', 'mæd', 'сумасшедший', 'Прилагательные'),
(573, 'Sad', 'sæd', 'грустный', 'Прилагательные'),
(574, 'Smart', 'smɑːt', 'умный', 'Прилагательные'),
(575, 'Aware', 'əˈweə(r)', 'осведомленный', 'Прилагательные'),
(576, 'Desperate', 'ˈdespərət', 'отчаянный', 'Прилагательные'),
(577, 'Critical', 'ˈkrɪtɪkl', 'критичный', 'Прилагательные'),
(578, 'Cute', 'kjuːt', 'милый', 'Прилагательные'),
(579, 'Competitive', 'kəmˈpetətɪv', 'конкурентный', 'Прилагательные'),
(580, 'Kind', 'kaɪnd', 'добрый', 'Прилагательные'),
(581, 'Capable', 'ˈkeɪpəbl', 'способный', 'Прилагательные'),
(582, 'Sexy', 'ˈseksi', 'сексуальный', 'Прилагательные'),
(583, 'Crazy', 'ˈkreɪzi', 'сумасшедший', 'Прилагательные'),
(584, 'To flirt', 'flɜːt', 'флиртовать', NULL),
(585, 'Date', 'deɪt', 'свидание; встречаться', NULL),
(586, 'To swipe', 'swaɪp', 'провести пальцем (например, вправо в Тиндере)', NULL),
(587, 'To hang out', 'ˈhæŋ aʊt', 'тусоваться, проводить время', NULL),
(588, 'To ghost', 'gəʊst', 'резко прекращать общение', NULL),
(589, 'To hook up with', 'ˈhʊk ʌp wɪð', 'замутить с кем-то', NULL),
(590, 'Match', 'mætʃ', 'совпадение', NULL),
(591, 'To text', 'tekst', 'написать сообщение', NULL),
(592, 'DM', 'ˌdiː ˈem', 'личное сообщение', NULL),
(593, 'Profile', 'ˈprəʊfaɪl', 'профиль (например, в соцсети)', NULL),
(594, 'Traveller', 'ˈtrævələ(r)', 'путешественник', NULL),
(595, 'Music', 'ˈmjuːzɪk', 'музыка', NULL),
(596, 'Road', 'rəʊd', 'дорога', NULL),
(597, 'Sport', 'spɔːt', 'спорт', NULL),
(598, 'Game', 'geɪm', 'игра', NULL),
(599, 'Film', 'fɪlm', 'фильм', NULL),
(600, 'Beauty', 'ˈbjuːti', 'красотка', NULL),
(601, 'Foodie', 'ˈfuːdi', 'гурман', NULL),
(602, 'Rich', 'rɪtʃ', 'богатый', NULL),
(603, 'Fashion', 'ˈfæʃn', 'мода', NULL),
(604, 'Style', 'staɪl', 'стиль', NULL),
(605, 'Tattoo', 'təˈtuː', 'татуировка', NULL),
(606, 'Piercing', 'ˈpɪəsɪŋ', 'пирсинг', NULL),
(607, 'Band', 'bænd', 'группа', NULL),
(608, 'Vegan', 'ˈviːgən', 'веган', NULL),
(609, 'Meat', 'miːt', 'мясо', NULL),
(610, 'Dessert', 'dɪˈzɜːt', 'десерт', NULL),
(611, 'Coffee', 'ˈkɒfi', 'кофе', NULL),
(612, 'Beer', 'bɪə(r)', 'пиво', NULL),
(613, 'Drama', 'ˈdrɑːmə', 'драма', NULL),
(614, 'Shot', 'ʃɒt', 'шот', NULL),
(615, 'Drunk', 'drʌŋk', 'выпивший', NULL),
(616, 'High', 'haɪ', 'высокий', NULL),
(617, 'To smoke', 'sməʊk', 'курить', NULL),
(618, 'Road trip', 'ˈrəʊd trɪp', 'автопутешествие', NULL),
(619, 'Workout', 'ˈwɜːkaʊt', 'тренировка', NULL),
(620, 'Cafe', 'ˈkæfeɪ', 'кафе', NULL),
(621, 'Mood', 'muːd', 'настроение', NULL),
(622, 'Laugh', 'lɑːf', 'смех', NULL),
(623, 'Joke', 'dʒəʊk', 'шутка', NULL),
(624, 'Sense', 'sens', 'чувство', NULL),
(625, 'Sarcastic', 'sɑːˈkæstɪk', 'саркастический', NULL),
(626, 'Irony', 'ˈaɪrəni', 'ирония', NULL),
(627, 'To tease', 'tiːz', 'дразнить', NULL),
(628, 'To fight', 'faɪt', 'ссориться, драться', NULL),
(629, 'To argue', 'ˈɑːgjuː', 'спорить', NULL),
(630, 'To lie', 'laɪ', 'лгать', NULL),
(631, 'Ex', 'eks', 'бывший', NULL),
(632, 'To cheat', 'tʃiːt', 'изменять', NULL),
(633, 'Anniversary', 'ˌænɪˈvɜːsəri', 'годовщина', NULL),
(634, 'To break up', 'ˈbreɪk ʌp', 'расстаться', NULL),
(635, 'Heartbreaking', 'ˈhɑːtbreɪkɪŋ', 'душераздирающий', NULL),
(636, 'Friends', 'frendz', 'друзья', NULL),
(637, 'Relationship', 'rɪˈleɪʃnʃɪp', 'отношения', NULL),
(638, 'Single', 'ˈsɪŋgl', 'один, без пары', NULL),
(639, 'Romantic', 'rəʊˈmæntɪk', 'романтический', NULL),
(640, 'Weekend', 'ˌwiːkˈend', 'выходные', NULL),
(641, 'Concert', 'ˈkɒnsət', 'концерт', NULL),
(642, 'TV series', 'ˌtiː ˈviː ˈsɪəriːz', 'сериал', NULL),
(643, 'Children', 'ˈtʃɪldrən', 'дети (в формальном общении)', NULL),
(644, 'Friendship', 'ˈfrendʃɪp', 'дружба', NULL),
(645, 'Married', 'ˈmærid', 'замужем/женат', NULL),
(646, 'Kids', 'kɪdz', 'дети (в неформальном общении)', NULL),
(647, 'Cat', 'kæt', 'кошка', NULL),
(648, 'Dog', 'dɒg', 'собака', NULL),
(649, 'Dancing', 'ˈdɑːnsɪŋ', 'танцы', NULL),
(650, 'To crush on', 'krʌʃ', 'влюбиться', NULL),
(651, 'Family', 'ˈfæməli', 'семья', NULL),
(652, 'Early', 'ˈɜːli', 'ранний', NULL),
(653, 'Bed', 'bed', 'кровать', NULL),
(654, 'Apartment', 'əˈpɑːtmənt', 'квартира, апартаменты', NULL),
(655, 'Ride', 'raɪd', 'поездка', NULL),
(656, 'Car', 'kɑː(r)', 'автомобиль', NULL),
(657, 'Bar', 'bɑː(r)', 'бар', NULL),
(658, 'Park', 'pɑːk', 'парк', NULL),
(659, 'Fiancé', 'fiˈɒnseɪ', 'жених', NULL),
(660, 'To dump', 'dʌmp', 'бросить', NULL),
(661, 'Spouse', 'spaʊs, spaʊz', 'супруг(-а)', NULL),
(662, 'Sight', 'saɪt', 'взгляд', NULL),
(663, 'Boyfriend', 'ˈbɔɪfrend', 'парень, бойфренд', NULL),
(664, 'Girlfriend', 'ˈgɜːlfrend', 'подруга, любимая девушка', NULL),
(665, 'Dinner', 'ˈdɪnə(r)', 'ужин', NULL),
(666, 'Partner', 'ˈpɑːtnə(r)', 'партнер', NULL),
(667, 'Gift', 'gɪft', 'подарок', NULL),
(668, 'Wine', 'waɪn', 'вино', NULL),
(669, 'To chat', 'tʃæt', 'беседовать', NULL),
(670, 'Shy', 'ʃaɪ', 'застенчивый', NULL),
(671, 'Nervous', 'ˈnɜːvəs', 'нервный', NULL),
(672, 'Couple', 'ˈkʌpl', 'пара', NULL),
(673, 'Passionate', 'ˈpæʃənət', 'страстный', NULL),
(674, 'Gaze', 'geɪz', 'взгляд', NULL),
(675, 'Unforgettable', 'ˌʌnfəˈgetəbl', 'незабываемый', NULL),
(676, 'To forget', 'fəˈget', 'забывать', NULL),
(677, 'To forgive', 'fəˈgɪv', 'прощать', NULL),
(678, 'To hug', 'hʌg', 'обнимать', NULL),
(679, 'Special', 'ˈspeʃl', 'особенный', NULL),
(680, 'Sparkle', 'ˈspɑːkl', 'искра', NULL),
(681, 'Bond', 'bɒnd', 'связь', NULL),
(682, 'Podcast', 'ˈpɒdkɑːst', 'подкаст', NULL),
(683, 'Pastime', 'ˈpɑːstaɪm', 'времяпрепровождение', NULL),
(684, 'Baking', 'ˈbeɪkɪŋ', 'выпечка', NULL),
(685, 'Cooking', 'ˈkʊkɪŋ', 'готовка', NULL),
(686, 'Yoga', 'ˈjəʊgə', 'йога', NULL),
(687, 'Fitness', 'ˈfɪtnəs', 'фитнес', NULL),
(688, 'Meditation', 'ˌmedɪˈteɪʃn', 'медитация', NULL),
(689, 'Feeling', 'ˈfiːlɪŋ', 'чувство', NULL),
(690, 'Jealous', 'ˈdʒeləs', 'ревнивый', NULL),
(691, 'Divorce', 'dɪˈvɔːs', 'развод', NULL),
(692, 'Soulmate', 'ˈsəʊlmeɪt', 'родственная душа', NULL),
(693, 'Tolerance', 'ˈtɒlərəns', 'терпимость', NULL),
(694, 'Reunion', 'ˌriːˈjuːniən', 'воссоединение', NULL),
(695, 'To cuddle', 'ˈkʌdl', 'обнимать', NULL),
(696, 'Intimacy', 'ˈɪntɪməsi', 'близость', NULL),
(697, 'Sensual', 'ˈsenʃuəl', 'чувственный', NULL),
(698, 'Affection', 'əˈfekʃn', 'привязанность', NULL),
(699, 'Embrace', 'ɪmˈbreɪs', 'объятие', NULL),
(700, 'One-night stand', 'ˌwʌn naɪt ˈstænd', 'секс на одну ночь', NULL),
(701, 'Pleasure', 'ˈpleʒə(r)', 'удовольствие', NULL),
(702, 'Connection', 'kəˈnekʃn', 'связь', NULL),
(703, 'Chemistry', 'ˈkemɪstri', 'химия, физическая совместимость', NULL),
(704, 'Passion', 'ˈpæʃn', 'страсть', NULL),
(705, 'Desire', 'dɪˈzaɪə(r)', 'желание', NULL),
(706, 'Monogamy', 'məˈnɒgəmi', 'моногамия', NULL),
(707, 'Polyamory', 'ˌpɒliˈæməri', 'полиамория', NULL),
(708, 'Erotic', 'ɪˈrɒtɪk', 'эротический', NULL),
(709, 'Fantasy', 'ˈfæntəsi', 'фантазия', NULL),
(710, 'Kink', 'kɪŋk', 'кинк', NULL),
(711, 'Experimentation', 'ɪkˌsperɪmenˈteɪʃn', 'эксперименты', NULL),
(712, 'Threesome', 'ˈθriːsəm', 'секс втроем', NULL),
(713, 'Trust', 'trʌst', 'доверие', NULL),
(714, 'Safety', 'ˈseɪfti', 'безопасность', NULL),
(715, 'Contraception', 'ˌkɒntrəˈsepʃn', 'контрацепция', NULL),
(716, 'Foreplay', 'ˈfɔːpleɪ', 'прелюдия', NULL),
(717, 'To caress', 'kəˈres', 'ласкать', NULL),
(718, 'To kiss', 'kɪs', 'целовать', NULL),
(719, 'To touch', 'tʌtʃ', 'прикасаться', NULL),
(720, 'Horny', 'ˈhɔːni', 'возбужденный', NULL),
(721, 'Privacy', 'ˈprɪvəsi', 'уединение', NULL),
(722, 'Orgasm', 'ˈɔːgæzəm', 'оргазм', NULL),
(723, 'Satisfaction', 'ˌsætɪsˈfækʃn', 'удовлетворение', NULL),
(724, 'Climax', 'ˈklaɪmæks', 'кульминация', NULL),
(725, 'Taboo', 'təˈbuː', 'табу', NULL),
(726, 'Fetish', 'ˈfetɪʃ', 'фетиш', NULL),
(727, 'Lover', 'ˈlʌvə(r)', 'любовник, возлюбленный', NULL),
(728, 'Imagination', 'ɪˌmædʒɪˈneɪʃn', 'воображение', NULL),
(729, 'Husband', 'ˈhʌzbənd', 'муж', NULL),
(730, 'Wife', 'waɪf', 'жена', NULL),
(731, 'Tenderness', 'ˈtendənəs', 'нежность', NULL),
(732, 'Lust', 'lʌst', 'похоть', NULL),
(733, 'Sexting', 'ˈsekstɪŋ', 'секстинг', NULL),
(734, 'Consent', 'kənˈsent', 'согласие', NULL),
(735, 'Boundaries', 'ˈbaʊndərɪz', 'границы', NULL),
(736, 'Communication', 'kəˌmjuːnɪˈkeɪʃn', 'коммуникация', NULL),
(737, 'Respect', 'rɪˈspekt', 'уважение', NULL),
(738, 'Delicacy', 'ˈdelɪkəsi', 'деликатность, чуткость', NULL),
(739, 'Spontaneity', 'ˌspɒntəˈneɪəti', 'спонтанность', NULL),
(740, 'Excitement', 'ɪkˈsaɪtmənt', 'возбуждение', NULL),
(741, 'Thrill', 'θrɪl', 'острые ощущения', NULL),
(742, 'Playful', 'ˈpleɪfl', 'игривый', NULL),
(743, 'Fun', 'fʌn', 'веселье', NULL),
(744, 'Seduction', 'sɪˈdʌkʃn', 'соблазнение', NULL),
(745, 'Courtship', 'ˈkɔːtʃɪp', 'ухаживания', NULL),
(746, 'Afterglow', 'ˈɑːftəgləʊ', 'посторгазменное состояние', NULL),
(747, 'Fulfilment', 'fʊlˈfɪlmənt', 'удовлетворение', NULL),
(748, 'Release', 'rɪˈliːs', 'разрядка, выпуск', NULL),
(749, 'Response', 'rɪˈspɒns', 'реакция, ответ', NULL),
(750, 'Sensitivity', 'ˌsensəˈtɪvəti', 'чувствительность', NULL),
(751, 'Arousal', 'əˈraʊzl', 'возбуждение', NULL),
(752, 'Stimulation', 'ˌstɪmjuˈleɪʃn', 'стимуляция', NULL),
(753, 'Libido', 'lɪˈbiːdəʊ', 'либидо', NULL),
(754, 'Drive', 'draɪv', 'влечение', NULL),
(755, 'Energy', 'ˈenədʒi', 'энергия', NULL),
(756, 'Vitality', 'vaɪˈtæləti', 'живость, энергичность', NULL),
(757, 'Fertility', 'fəˈtɪləti', 'фертильность', NULL),
(758, 'Pregnancy', 'ˈpregnənsi', 'беременность', NULL),
(759, 'Protection', 'prəˈtekʃn', 'защита', NULL),
(760, 'Wellness', 'ˈwelnəs', 'хорошее самочувствие', NULL),
(761, 'Anatomy', 'əˈnætəmi', 'анатомия', NULL),
(762, 'Genitals', 'ˈdʒenɪtlz', 'гениталии', NULL),
(763, 'Reproduction', 'ˌriːprəˈdʌkʃn', 'размножение', NULL),
(764, 'Gender', 'ˈdʒendə(r)', 'гендер', NULL),
(765, 'Orientation', 'ˌɔːriənˈteɪʃn', 'ориентация', NULL),
(766, 'Identity', 'aɪˈdentəti', 'идентичность', NULL),
(767, 'Expression', 'ɪkˈspreʃn', 'выражение', NULL),
(768, 'Lifestyle', 'ˈlaɪfstaɪl', 'стиль жизни', NULL),
(769, 'Community', 'kəˈmjuːnəti', 'сообщество', NULL),
(770, 'Commitment', 'kəˈmɪtmənt', 'обязательство', NULL),
(771, 'Marriage', 'ˈmærɪdʒ', 'брак', NULL),
(772, 'Romance', 'rəʊˈmæns, ˈrəʊmæns', 'роман, романтика', NULL),
(773, 'Infatuation', 'ɪnˌfætʃuˈeɪʃn', 'увлечение', NULL),
(774, 'Rejection', 'rɪˈdʒekʃn', 'отказ', NULL),
(775, 'Salary', 'ˈsæləri', 'зарплата', NULL),
(776, 'Profit', 'ˈprɒfɪt', 'прибыль', NULL),
(777, 'Task', 'tɑːsk', 'задача', NULL),
(778, 'Project', 'ˈprɒdʒekt', 'проект', NULL),
(779, 'Deadline', 'ˈdedlaɪn', 'срок выполнения, дедлайн', NULL),
(780, 'Schedule', 'ˈʃedjuːl', 'график', NULL),
(781, 'Skill', 'skɪl', 'навык', NULL),
(782, 'Remote', 'rɪˈməʊt', 'удаленный', NULL),
(783, 'Goal', 'gəʊl', 'цель', NULL),
(784, 'Success', 'səkˈses', 'успех', NULL),
(785, 'Investment', 'ɪnˈvestmənt', 'инвестиция', NULL),
(786, 'Sale', 'seɪl', 'продажа', NULL),
(787, 'Purchase', 'ˈpɜːtʃəs', 'покупка', NULL),
(788, 'Stock', 'stɒk', 'акции', NULL),
(789, 'Growth', 'grəʊθ', 'рост', NULL),
(790, 'IRL', 'ˌaɪ ɑːr ˈel', 'in real life, в реальной жизни', NULL),
(791, 'To yeet', 'jiːt', 'кидать', NULL),
(792, 'Bae', 'beɪ', 'короткая версия слова baby', NULL),
(793, 'Swag', 'swæg', 'очень классный', NULL),
(794, 'Basic', 'ˈbeɪsɪk', 'обычный, неоригинальный', NULL),
(795, 'To slay', 'sleɪ', 'отлично справляться с чем-то', NULL),
(796, 'Extra', 'ˈekstrə', 'чрезмерный', NULL),
(797, 'Damn', 'dæm', 'черт', NULL),
(798, 'LOL', 'lɒl, ˌel əʊ ˈel', 'laughing out loud, смеяться в голос', NULL),
(799, 'To cancel', 'ˈkænsl', '«отменять», переставать поддерживать кого-то', NULL),
(800, 'Facepalm', 'ˈfeɪspɑːm', 'фейспалм, он же «рукалицо»', NULL),
(801, 'Noob', 'nuːb', 'новичок', NULL),
(802, 'Epic', 'ˈepɪk', 'легендарный, лучший', NULL),
(803, 'To fail', 'feɪl', 'провалиться', NULL),
(804, 'ROFL', 'ˈrɒfl', 'rolling on the floor laughing, смеяться до слез', NULL),
(805, 'TBH', 'ˌtiː biː ˈeɪtʃ', 'to be honest, честно говоря', NULL),
(806, 'BRB', 'ˌbiː ɑː ˈbiː', 'be right back, скоро вернусь', NULL),
(807, 'IMO/IMHO', 'ˌaɪ em ˈəʊ, ˌaɪ em eɪtʃ ˈəʊ', 'in my (humble) opinion, по моему (скромному) мнению', NULL),
(808, 'Kudos', 'ˈkjuːdɒs', 'браво, респект', NULL),
(809, 'NSFW', 'ˌen es ef ˈdʌbljuː', 'not safe for work, что-то достойное цензуры', NULL),
(810, 'Viral', 'ˈvaɪrəl', 'популярный, вирусный', NULL),
(811, 'Selfie', 'ˈselfi', 'селфи', NULL),
(812, 'Gig', 'gɪg', 'концерт', NULL),
(813, 'Earworm', 'ˈɪəwɜːm', 'навязчивая мелодия', NULL),
(814, 'Lame', 'leɪm', 'скучный, плохой', NULL),
(815, 'Gross', 'grəʊs', 'отвратительно', NULL),
(816, 'ASAP', 'ˌeɪ es eɪ ˈpiː, ˈeɪsæp', 'as soon as possible, как можно скорее', NULL),
(817, 'OMG', 'ˌəʊ em ˈdʒiː', 'oh my God, о боже', NULL),
(818, 'ETA', 'ˌiː tiː ˈeɪ', 'estimated time of arrival, примерное время прибытия', NULL),
(819, 'BTW', 'ˌbiː tiː ˈdʌbljuː', 'by the way, кстати', NULL),
(820, 'Feed', 'fiːd', 'лента (новостей)', NULL),
(821, 'Like', 'laɪk', 'лайк', NULL),
(822, 'Comment', '''kɒment', 'комментарий', NULL),
(823, 'Post', 'pəʊst', 'пост, выкладывать пост', NULL),
(824, 'To share', 'ʃeə(r)', 'делиться в соцсетях', NULL),
(825, 'To follow', '''fɒləʊ', 'подписаться, отслеживать', NULL),
(826, 'To unfollow', 'ˌʌn''fɒləʊ', 'отписаться', NULL),
(827, 'Bio', 'baɪəʊ', 'биография в шапке профиля', NULL),
(828, 'Hashtag', '''hæʃtæg', 'хештег', NULL),
(829, 'Tag', 'tæg', 'тег', NULL),
(830, 'Filter', '''fɪltə(r)', 'фильтр', NULL),
(831, 'Caption', '''kæpʃn', 'подпись', NULL),
(832, 'Reels', 'riːlz', 'рилс', NULL),
(833, 'Algorithm', '''ælgərɪðəm', 'алгоритм', NULL),
(834, 'Engagement', 'ɪn''geɪdʒmənt', 'вовлечение в соцсетях', NULL),
(835, 'Follower', '''fɒləʊə(r)', 'подписчик', NULL),
(836, 'Creator', 'kri''eɪtə(r)', 'креатор', NULL),
(837, 'Shout-out', '''ʃaʊt aʊt', 'публичная благодарность', NULL),
(838, 'Repost', 'rɪ''pəʊst', 'репост', NULL),
(839, 'Trend', 'trend', 'тренд', NULL),
(840, 'Theme', 'θiːm', 'тема', NULL),
(841, 'Brand', 'brænd', 'бренд', NULL),
(842, 'Highlights', '''haɪlaɪts', 'хайлайты (закрепленные сторис в соцсетях)', NULL),
(843, 'Archive', '''ɑːkaɪv', 'архив', NULL),
(844, 'Vlog', 'vlɒg', 'влог, видеоблог', NULL),
(845, 'Blogger', '''blɒgə(r)', 'блогер', NULL),
(846, 'Fashion', '''fæʃn', 'мода', NULL),
(847, 'Promo (promotion)', '''prəʊməʊ, [prə''məʊʃn]', 'промо', NULL),
(848, 'Affiliate', 'ə''fɪliət', 'партнер', NULL),
(849, 'Ad (advertisement)', 'æd, [əd''vɜːtɪsmənt]', 'реклама', NULL),
(850, 'Sponsored', '''spɒnsəd', 'спонсируемый', NULL),
(851, 'Emoji', 'ɪ''məʊdʒi', 'эмодзи', NULL),
(852, 'Clickbait', '''klɪkbeɪt', 'кликбейт (контент только с целью кликов)', NULL),
(853, 'Link', 'lɪŋk', 'ссылка', NULL),
(854, 'Geotag', '''dʒiːəʊtæg', 'геометка', NULL),
(855, 'Location', 'ləʊ''keɪʃn', 'местоположение', NULL),
(856, 'Notification', 'ˌnəʊtɪfɪ''keɪʃn', 'уведомление', NULL),
(857, 'Verified', '''verɪfaɪd', 'проверенный', NULL),
(858, 'Icon', '''aɪkɒn', 'икона, иконка', NULL),
(859, 'Collaboration', 'kəˌlæbə''reɪʃn', 'коллаборация', NULL),
(860, 'Challenge', '''tʃælɪndʒ', 'челлендж', NULL),
(861, 'Tutorial', 'tjuː''tɔːriəl', 'обучающий контент', NULL),
(862, 'Review', 'rɪ''vjuː', 'обзор', NULL),
(863, 'Unboxing', 'ˌʌn''bɒksɪŋ', 'распаковка', NULL),
(864, 'Giveaway', '''gɪvəweɪ', 'конкурс с призами в соцсетях', NULL),
(865, 'Contest', '''kɒntest', 'конкурс', NULL),
(866, 'FOMO (fear of missing out)', '''fəʊməʊ', 'страх упустить что-то важное или интересное', NULL),
(867, 'BFF (best friend forever)', 'ˌbiː ef ''ef', 'лучший друг навеки', NULL),
(868, 'Live', 'laɪv', 'в прямом эфире', NULL),
(869, 'Shopping', '''ʃɒpɪŋ', 'шопинг', NULL),
(870, 'Discovery', 'dɪ''skʌvəri', 'открытие', NULL),
(871, 'Niche', 'niːʃ, nɪtʃ', 'ниша', NULL),
(872, 'To connect', 'kə''nekt', 'связываться', NULL),
(873, 'To inspire', 'ɪn''spaɪə(r)', 'вдохновляться', NULL),
(874, 'Culture', '''kʌltʃə(r)', 'культура', NULL),
(875, 'Creativity', 'ˌkriːeɪ''tɪvəti', 'креативность', NULL),
(876, 'Authenticity', 'ˌɔːθen''tɪsəti', 'аутентичность', NULL),
(877, 'Visuals', '''vɪʒuəlz', 'визуальные эффекты', NULL),
(878, 'Portfolio', 'pɔːt''fəʊliəʊ', 'портфолио', NULL),
(879, 'Technology', 'tek''nɒlədʒi', 'технология', NULL),
(880, 'Online', 'ˌɒn''laɪn', 'онлайн', NULL),
(881, 'App', 'æp', 'приложение', NULL),
(882, 'Search', 'sɜːtʃ', 'поиск', NULL),
(883, 'To spill', 'spɪl', 'проливать', NULL),
(884, 'Should', 'ʃʊd', 'следует', NULL),
(885, 'To say', 'seɪ', 'сказать', NULL),
(886, 'To believe', 'bɪ''liːv', 'верить', NULL),
(887, 'To make', 'meɪk', 'делать', NULL),
(888, 'To tell', 'tel', 'рассказывать', NULL),
(889, 'To give', 'gɪv', 'давать', NULL),
(890, 'To get', 'get', 'получать', NULL),
(891, 'To know', 'nəʊ', 'знать', NULL),
(892, 'To find', 'faɪnd', 'находить', NULL),
(893, 'To hope', 'həʊp', 'надеяться', NULL),
(894, 'To kill', 'kɪl', 'убивать', NULL),
(895, 'To look', 'lʊk', 'смотреть, выглядеть', NULL),
(896, 'To like', 'laɪk', 'нравиться', NULL),
(897, 'To worry', '''wʌri', 'беспокоиться', NULL),
(898, 'To listen', '''lɪsn', 'слушать', NULL),
(899, 'To use', 'juːz', 'использовать', NULL),
(900, 'To change', 'tʃeɪndʒ', 'менять', NULL),
(901, 'To try', 'traɪ', 'пытаться, пробовать', NULL),
(902, 'To want', 'wɒnt', 'хотеть', NULL),
(903, 'To sound', 'saʊnd', 'звучать', NULL),
(904, 'To let', 'let', 'позволять', NULL),
(905, 'To run', 'rʌn', 'бежать', NULL),
(906, 'To go', 'gəʊ', 'идти', NULL),
(907, 'To cost', 'kɒst', 'стоить', NULL),
(908, 'To take', 'teɪk', 'брать', NULL),
(909, 'To think', 'θɪŋk', 'думать', NULL),
(910, 'To stay', 'steɪ', 'оставаться', NULL),
(911, 'To lose', 'luːz', 'терять', NULL),
(912, 'To support', 'sə''pɔːt', 'поддерживать', NULL),
(913, 'To prefer', 'prɪ''fɜː(r)', 'предпочитать', NULL),
(914, 'To talk', 'tɔːk', 'разговаривать', NULL),
(915, 'To ask', 'ɑːsk', 'спрашивать', NULL),
(916, 'To answer', '''ɑːnsə(r)', 'отвечать', NULL),
(917, 'To start', 'stɑːt', 'начинать', NULL),
(918, 'To eat', 'iːt', 'есть', NULL),
(919, 'To join', 'dʒɔɪn', 'присоединяться', NULL),
(920, 'To see', 'siː', 'смотреть', NULL),
(921, 'To love', 'lʌv', 'любить', NULL),
(922, 'To remain', 'rɪ''meɪn', 'оставаться', NULL),
(923, 'To put', 'pʊt', 'класть, помещать', NULL),
(924, 'To reach', 'riːtʃ', 'достигать', NULL),
(925, 'To cut', 'kʌt', 'резать', NULL),
(926, 'To fall', 'fɔːl', 'падать', NULL),
(927, 'To wait', 'weɪt', 'ждать', NULL),
(928, 'To write', 'raɪt', 'писать', NULL),
(929, 'To bring', 'brɪŋ', 'приносить', NULL),
(930, 'To realise', '''riːəlaɪz, ''rɪəlaɪz', 'понимать', NULL),
(931, 'To involve', 'ɪn''vɒlv', 'вовлекать', NULL),
(932, 'To reduce', 'rɪ''dʒuːs', 'сокращать', NULL),
(933, 'To concern', 'kən''sɜːn', 'беспокоить', NULL),
(934, 'To fly', 'flaɪ', 'летать', NULL),
(935, 'To raise', 'reɪz', 'поднимать, повышать', NULL),
(936, 'To manage', '''mænɪdʒ', 'управлять, справляться', NULL),
(937, 'To apply', 'ə''plaɪ', 'обращаться; применять', NULL),
(938, 'To spend', 'spend', 'проводить; тратить', NULL),
(939, 'To keep', 'kiːp', 'хранить', NULL),
(940, 'To smell', 'smel', 'пахнуть, нюхать', NULL),
(941, 'To begin', 'bɪˈgɪn', 'начинать', NULL),
(942, 'To enjoy', 'ɪnˈdʒɔɪ', 'получать удовольствие', NULL),
(943, 'To pretend', 'prɪˈtend', 'притворяться', NULL),
(944, 'To stop', 'stɒp', 'останавливаться', NULL),
(945, 'To build', 'bɪld', 'строить', NULL),
(946, 'To meet', 'miːt', 'встречаться, знакомиться', NULL),
(947, 'To stand', 'stænd', 'стоять', NULL),
(948, 'To continue', 'kənˈtɪnjuː', 'продолжать', NULL),
(949, 'To buy', 'baɪ', 'покупать', NULL),
(950, 'To walk', 'wɔːk', 'гулять', NULL),
(951, 'To open', 'ˈəʊpən', 'открывать', NULL),
(952, 'To offer', 'ˈɒfə(r)', 'предлагать', NULL),
(953, 'To imagine', 'ɪˈmædʒɪn', 'воображать', NULL),
(954, 'To send', 'send', 'отправлять', NULL),
(955, 'To die', 'daɪ', 'умирать', NULL),
(956, 'To serve', 'sɜːv', 'служить', NULL),
(957, 'To appear', 'əˈpɪə(r)', 'появляться', NULL),
(958, 'To return', 'rɪˈtɜːn', 'возвращаться', NULL),
(959, 'To consider', 'kənˈsɪdə(r)', 'рассматривать, учитывать', NULL),
(960, 'To remember', 'rɪˈmembə(r)', 'помнить', NULL),
(961, 'To win', 'wɪn', 'побеждать', NULL),
(962, 'To read', 'riːd', 'читать', NULL),
(963, 'To expect', 'ɪkˈspekt', 'ожидать', NULL),
(964, 'To break', 'breɪk', 'прерывать, ломать', NULL),
(965, 'To grow', 'grəʊ', 'расти', NULL),
(966, 'To add', 'æd', 'добавлять', NULL),
(967, 'To allow', 'əˈlaʊ', 'позволять', NULL),
(968, 'To speak', 'spiːk', 'говорить', NULL),
(969, 'To create', 'kriˈeɪt', 'создавать', NULL),
(970, 'To avoid', 'əˈvɔɪd', 'избегать', NULL),
(971, 'To sleep', 'sliːp', 'спать', NULL),
(972, 'To understand', 'ˌʌndəˈstænd', 'понимать', NULL),
(973, 'To lead', 'liːd', 'вести', NULL),
(974, 'To learn', 'lɜːn', 'учить, запоминать', NULL),
(975, 'To set', 'set', 'устанавливать', NULL),
(976, 'To include', 'ɪnˈkluːd', 'включать', NULL),
(977, 'To pay', 'peɪ', 'платить', NULL),
(978, 'To feel', 'fiːl', 'чувствовать', NULL),
(979, 'To happen', 'ˈhæpən', 'происходить', NULL),
(980, 'To sit', 'sɪt', 'сидеть', NULL),
(981, 'To provide', 'prəˈvaɪd', 'предоставлять', NULL),
(982, 'Must', 'mʌst', 'быть обязанным', NULL),
(983, 'To hold', 'həʊld', 'держать', NULL),
(984, 'To live', 'lɪv', 'жить', NULL),
(985, 'To play', 'pleɪ', 'играть', NULL),
(986, 'To leave', 'liːv', 'покидать, оставлять', NULL),
(987, 'To seem', 'siːm', 'казаться', NULL),
(988, 'To hear', 'hɪə(r)', 'слышать', NULL),
(989, 'To care', 'keə(r)', 'заботиться', NULL),
(990, 'To show', 'ʃəʊ', 'показывать', NULL),
(991, 'To turn', 'tɜːn', 'поворачивать', NULL),
(992, 'To help', 'help', 'помогать', NULL),
(993, 'To mean', 'miːn', 'иметь в виду', NULL),
(994, 'To become', 'bɪˈkʌm', 'становиться', NULL),
(995, 'To need', 'niːd', 'нуждаться', NULL),
(996, 'To call', 'kɔːl', 'звать', NULL),
(997, 'May', 'meɪ', 'мочь', NULL),
(998, 'To study', 'ˈstʌdi', 'изучать', NULL),
(999, 'To behave', 'bɪˈheɪv', 'вести себя', NULL),
(1000, 'To suggest', 'səˈdʒest', 'предлагать', NULL)
ON CONFLICT (id) DO UPDATE SET
    word = EXCLUDED.word, ipa = EXCLUDED.ipa,
    translation = EXCLUDED.translation, pos = EXCLUDED.pos;
